name: "02-gh-pages-rebuild-part-1" # Note: workflow name is used on workflow 04
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: read

jobs:
  initialize:
    name: Build Basic Site
    runs-on: ubuntu-latest
    outputs:
      pull_requests: ${{ steps.get-prs.outputs.pull_requests }}

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v3.5.2
    - name: Get Pull Requests from Github api
      id: get-prs
      run: |
         gh pr list -s open --json url,author,number,title,headRefName 
         gh pr list -s open --json url,author,number,title,headRefName > prs.json
         cat prs.json
         pull_requests=`cat prs.json`
         echo "pull_requests=${pull_requests}"
         echo "pull_requests=${pull_requests}" >> "$GITHUB_OUTPUT"
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version-file: 'frontend/package.json'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
 
  build-javadoc-main:
    name: a - Javadoc (main)
    runs-on: ubuntu-latest
    needs: [initialize]
    env:
      destination: target/site/apidocs   
    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v3.5.2
    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v3
      with:
         distribution: semeru # See: https://github.com/actions/setup-java#supported-distributions
         java-version-file: ./.java-version
  
    - name: Build javadoc
      run: mvn -DskipTests javadoc:javadoc

    - name: Upload to artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
          name: javadoc
          path: ${{ env.destination }}
  
  
  
  build-jacoco-main:
    name: c - Jacoco (main)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [initialize]
    env:
      destination: target/site/jacoco  

    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v3
      with:
         distribution: semeru # See: https://github.com/actions/setup-java#supported-distributions
         java-version-file: ./.java-version
  
    - name: Build with Maven
      continue-on-error: true
      env:
        TEST_PROPERTIES: ${{ secrets.TEST_PROPERTIES }}
      run: mvn -B test jacoco:report verify

    - name: Upload to artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
          name: jacoco
          path: ${{ env.destination }}

  build-pitest-main:
    name: d - Pitest (main)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [initialize]
    env:
      destination: target/pit-reports
      history_destination: target/pit-history

    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v3
      with:
         distribution: semeru # See: https://github.com/actions/setup-java#supported-distributions
         java-version-file: ./.java-version
    - name: create directories
      run: |
         mkdir -p ${{ env.destination }}
         mkdir -p ${{ env.history_destination }}

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2.27.0
      with:
        workflow: 02-gh-pages-rebuild-part-1.yml
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: ${{ env.branch_name }}
        name: pitest-main-history.bin
        path: ${{ env.history_destination}}
        check_artifacts: true
        if_no_artifact_found: warn

    - name: Copy artifact to pit-history/history.bin # specified in pom.xml as historyInputFile
      continue-on-error: true
      run: |
        historyFile=${{ env.history_destination}}/pitest-main-history.bin
        if [ -f "$historyFile" ] ; then
          cp $historyFile ${{ env.history_destination}}/history.bin
        fi

    - name: Build with Maven
      continue-on-error: true
      run: mvn test pitest:mutationCoverage -DmutationThreshold=100 

    - name: Upload Pitest History to Artifacts
      if: always() # always upload artifacts, even if tests fail
      uses: actions/upload-artifact@v3.1.2
      with:
        name: pitest-main-history.bin
        path: ${{ env.history_destination}}/history.bin

    - name: Upload to artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
          name: pitest
          path: ${{ env.destination }}

  

  a-build-javadoc-for-each-pr:
    name: a - Javadoc (${{ matrix.value.number }}, ${{ matrix.value.headRefName }})
    runs-on: ubuntu-latest
    if: ${{ needs.initialize.outputs.pull_requests != '[]' && needs.initialize.outputs.pull_requests != '' }}

    needs: [initialize]

    env:
      destination: target/site/apidocs   
    strategy:
      matrix:
        value: ${{ fromJSON(needs.initialize.outputs.pull_requests)}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2
      with:
        ref: ${{ matrix.value.headRefName }}
        fetch-depth: 1
        token: ${{ github.token }}

    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v3
      with:
         distribution: semeru # See: https://github.com/actions/setup-java#supported-distributions
         java-version-file: ./.java-version

    - name: Build javadoc
      run: mvn -DskipTests javadoc:javadoc
 
    - name: Upload javadoc to Artifacts
      if: always() # always upload artifacts, even if tests fail
      uses: actions/upload-artifact@v3.1.2
      with:
        name: prs-${{ matrix.value.number }}-javadoc
        path: ${{ env.destination }}
    
  

  c-build-jacoco-for-each-pr:
    name: c - Jacoco (${{ matrix.value.number }}, ${{ matrix.value.headRefName }})
    runs-on: ubuntu-latest
    if: ${{ needs.initialize.outputs.pull_requests != '[]' && needs.initialize.outputs.pull_requests != '' }}

    needs: [initialize]

    strategy:
      matrix:
        value: ${{ fromJSON(needs.initialize.outputs.pull_requests)}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2
      with:
        ref: ${{ matrix.value.headRefName }}
        fetch-depth: 1
        token: ${{ github.token }}

    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v3
      with:
         distribution: semeru # See: https://github.com/actions/setup-java#supported-distributions
         java-version-file: ./.java-version

    - name: Build with Maven
      continue-on-error: true
      env:
        TEST_PROPERTIES: ${{ secrets.TEST_PROPERTIES }}
      run: mvn -B test jacoco:report verify
 
    - name: Upload to artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
          name: prs-${{ matrix.value.number }}-jacoco
          path: target/site/jacoco

  d-build-pitest-for-each-pr:
    name: d - Pitest (${{ matrix.value.number }}, ${{ matrix.value.headRefName }})
    runs-on: ubuntu-latest
    if: ${{ needs.initialize.outputs.pull_requests != '[]' && needs.initialize.outputs.pull_requests != '' }}

    needs: [initialize]

    env:
      destination: target/pit-reports
      history_destination: target/pit-history

    strategy:
      matrix:
        value: ${{ fromJSON(needs.initialize.outputs.pull_requests)}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2
      with:
        ref: ${{ matrix.value.headRefName }}
        fetch-depth: 1
        token: ${{ github.token }}
    - name: create directories
      run: |
         mkdir -p ${{ env.destination }}
         mkdir -p ${{ env.history_destination }}

    - name: Figure out branch name
      id: get-branch-name
      run: | 
          BRANCH=$(echo "${{ matrix.value.headRefName }}" | sed 's/refs\/heads\///g')
          echo "branch_name=${BRANCH}"
          echo "branch_name=${BRANCH}" >> "$GITHUB_ENV"
    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v3
      with:
         distribution: semeru # See: https://github.com/actions/setup-java#supported-distributions
         java-version-file: ./.java-version

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2.27.0
      with:
        workflow: 02-gh-pages-rebuild-part-1.yml
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: ${{ env.branch_name }}
        name: pitest-${{ matrix.value.number }}-history.bin
        path: ${{ env.history_destination}}
        check_artifacts: true
        if_no_artifact_found: warn
  
    - name: Debugging output before mvn pitest ...
      run: |
        ls -lRt target

    - name: Build with Maven
      continue-on-error: true
      env:
        TEST_PROPERTIES: ${{ secrets.TEST_PROPERTIES }}
      run: mvn test pitest:mutationCoverage -DmutationThreshold=100 
  
    - name: Debugging output after mvn pitest ...
      run: |
        ls -lRt target

    - name: Upload Pitest History to Artifacts
      if: always() # always upload artifacts, even if tests fail
      uses: actions/upload-artifact@v3.1.2
      with:
        name: pitest-${{ matrix.value.number }}-history.bin
        path: ${{ env.history_destination}}/history.bin

    - name: Upload to artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
          name: prs-${{ matrix.value.number }}-pitest
          path: ${{ env.destination }}

  